spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xharktank
    username: admin
    password: Admin@1324

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
